'use strict';
const colors = require('colors');
colors.enabled = true;
console.log(colors.red('Richard'));
console.log(colors.yellow('Of'));
console.log(colors.bgYellow('York'));
console.log(colors.green('Gave'));
console.log(colors.cyan('Battle'));
console.log(colors.blue('In'));
console.log(colors.magenta('Vain'));